### PR TITLE
Fix encoding issues

### PR DESCRIPTION
**Pull request by tsdko**
The default Flask web server seems to have difficulties with Shift-JIS query strings, but the app does work when served via [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/)+[nginx](https://nginx.org/en/).

### CODE REVIEW

**Comment by Ruin0x11** [comment]
Hmm, I'm still getting decoding errors when testing `uwsgi` deployment:

```
  File "./elona.py", line 74, in text
    return Response(str.encode(response, "shift-jis"), mimetype='text/plain')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 15: ordinal not in range(128)
```

This is how I'm running the app currently:

```
uwsgi -s /tmp/elona_server.sock --manage-script-name --mount /elona_server=elona:app --virtualenv /home/ruin/uwsgi-tutorial --http :8000
```

Could you supply the configuration for your environment so I could replicate it here? Thank you for contributing.

**Comment by tsdko** [comment]
> ```
>  File "./elona.py", line 74, in text
>     return Response(str.encode(response, "shift-jis"), mimetype='text/plain')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 15: ordinal not in range(128)
> ```

Are you sure you're using the right branch? That line looks different on the `tsudoko/wtalk` remote branch.

Also, the `ascii` codec is (in most cases) used by default only when your locales are misconfigured or you're using Python 2.

> Could you supply the configuration for your environment so I could replicate it here?

 - No root privileges
 - Python 3.5.2
 - uwsgi and flask installed inside the `elona_server/venv` virtual environment

Run script (managed with `s6`, but should work without it):
```
#!/bin/sh
 
SOCKET_PATH="$HOME/.local/var/elona.socket"
 
cd /home/flan/.src/elona_server
. venv/bin/activate
 
exec uwsgi 2>&1 \
    -s "$SOCKET_PATH" \
    --manage-script-name \
    --callable app \
    --wsgi-file elona.py
```

Relevant nginx `location` block:
```
location / {
  include /etc/nginx/uwsgi_params;
  uwsgi_pass unix:/home/flan/.local/var/elona.socket;
}
```

**Comment by Ruin0x11** [comment]
My bad, I haven't worked with issues before. But strangely, I'm getting this error on the proper branch:

```  
SyntaxError: Non-ASCII character '\xe5' in file elona.py on line 47, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

I'm using the uwsgi+nginx combination. Could it be a locale/environment issue, or something else?

**Comment by tsdko** [comment]
Are you absolutely sure you're using Python 3.x? As far as I know, only Python 2.x requires the file encoding to be declared when there are non-ascii characters present.

**Comment by Ruin0x11** [comment]
Yes, that was it.

In the end, it's good to go.

**Pull request merged**
